# Generated by Django 2.0.7 on 2018-08-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermovielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='moviedb_id',
            field=models.CharField(default=None, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
