# Generated by Django 2.0.7 on 2018-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180805_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='details',
            field=models.CharField(max_length=1000),
        ),
    ]
