# Generated by Django 2.0.7 on 2018-08-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180805_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovielist',
            old_name='list_postition',
            new_name='list_position',
        ),
    ]
