# Generated by Django 2.0.7 on 2018-08-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_comments_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='userList',
        ),
        migrations.AddField(
            model_name='comments',
            name='commentOwner',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
