# Generated by Django 2.0.7 on 2018-08-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_moviereviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovielist',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Movies'),
        ),
    ]
